<a href="https://colab.research.google.com/github/gitmystuff/DTSC5810/blob/main/Final_Project/Shared_Links.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working with Shared Links

Getting the File ID

* In your shared folder / file right click on the file and click on Share
* Copy link
* Here is an example of a copied link: https://drive.google.com/file/d/1-4d1PMlIyFgjWNnpPs_aD3gvVSGME07s/view?usp=drive_link
* Find the ID which in this case is 1-4d1PMlIyFgjWNnpPs_aD3gvVSGME07s
* Replace the id for the link provided below

In [4]:
import pandas as pd

# https://drive.google.com/file/d/1-4d1PMlIyFgjWNnpPs_aD3gvVSGME07s/view?usp=drive_link
id = '1-4d1PMlIyFgjWNnpPs_aD3gvVSGME07s'
retail_data = pd.read_csv(f'https://docs.google.com/uc?id={id}')
retail_data.head()

,xy,Retailer_Age,Perindex,view,consider,NPS_Category,fake_zipcode,challenge,fake_name,fake_date_of_birth,...,Zone,fake_surname,hit,camera,fake_misc,attack,benefit,Growth,usually,son
0,'various',>5,62.69,0.421678,0.827503,Detractor,14325,0.03,Larry,1976-04-16,...,South,Anderson,0.827503,0.83,'outside',-0.653329,-1.412767,12.57,0.07,-0.676214
1,'cup',<=2,56.39,0.558836,1.105440,Detractor,94338,0.03,Mary,1927-09-28,...,East,Lewis,1.105440,1.11,'partner',0.186454,-1.866966,2.16,0.07,-0.369158
2,'a',>5,76.42,0.215908,0.410421,Passive,8638,0.03,Wendy,1978-03-29,...,North,Myers,0.410421,0.41,'guess',0.504987,-0.731430,7.66,0.07,-1.143617
3,'blood',>5,87.81,0.587220,1.199671,Promoter,18455,0.03,Thomas,1947-12-10,...,South,Johnson,1.199671,1.20,'hotel',-0.692910,-1.938667,3.48,0.07,1.899103
4,'require',>5,71.02,0.028028,0.059031,Passive,10024,0.03,Kevin,1928-12-12,...,East,Hawkins,0.059031,0.06,'general',0.825416,-0.091459,4.79,0.07,0.196910

In [5]:
# create / connect to database
import sqlite3

connection = sqlite3.connect('ccpz.db') # creates / connects to db named after my team
cursor = connection.cursor()

In [6]:
# df to sql
retail_data.to_sql('retail_data', connection, if_exists='fail')

121

In [12]:
# what are my original columns before getting messed up?
url = 'https://raw.githubusercontent.com/gitmystuff/Datasets/main/Retail_Data.csv'
original_data = pd.read_csv(url)
print(original_data.info())
print(original_data.columns)
' '.join(col for col in original_data.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Retailer      100 non-null    int64
 1   Zone          100 non-null    object
 2   Retailer_Age  100 non-null    object
 3   Perindex      99 non-null     float64
 4   Growth        100 non-null    float64
 5   NPS_Category  100 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 4.8+ KB
None
Index(['Retailer', 'Zone', 'Retailer_Age', 'Perindex', 'Growth',
       'NPS_Category'],
      dtype='object')

'Retailer Zone Retailer_Age Perindex Growth NPS_Category'

In [13]:
# get data from database by copying the columns above
import pandas as pd
cursor.execute("SELECT Retailer, Zone, Retailer_Age, Perindex, Growth, NPS_Category FROM retail_data;")
df = pd.DataFrame(cursor.fetchall())
df.columns = original_data.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Retailer      121 non-null    int64
 1   Zone          121 non-null    object
 2   Retailer_Age  121 non-null    object
 3   Perindex      119 non-null    float64
 4   Growth        121 non-null    float64
 5   NPS_Category  121 non-null    object
dtypes: float64(2), int64(1), object(3)
memory usage: 5.8+ KB

In [ ]:
# clean up such as deleteing duplicate rows